# Generated by Django 3.2.4 on 2021-08-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=30)),
                ('ProductPrice', models.DecimalField(decimal_places=2, max_digits=13)),
                ('ProductImage', models.ImageField(blank=True, db_column='ProductImage', upload_to='')),
                ('ProductDiscription', models.CharField(max_length=30)),
                ('ProductDiscount', models.DecimalField(decimal_places=2, max_digits=13)),
            ],
        ),
    ]
