# Generated by Django 3.2.4 on 2021-08-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProductRating',
            field=models.IntegerField(default=0),
        ),
    ]
